
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 26 00:43:38 EDT 2019
//----------------------------------------------------

package rr.tool.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ID = 6;
  public static final int BAR = 3;
  public static final int error = 1;
  public static final int CPAREN = 5;
  public static final int OPAREN = 4;
  public static final int COLON = 2;
  public static final int EOF = 0;

  /* non terminals */
  static final int ToolSpec = 0;
}

